project:
  type: website
 
#Configuration de la langue 
lang: fr

website:
  title: "*Gabonese Wrist 🇬🇦*"
  back-to-top-navigation: true
  site-url: 'http://gabonesewrist.com/'
  google-analytics: 'G-WE15K3S8JT'

  page-footer:
    background: primary
    foreground: white
    
    left:
      - text : Website made with **Quarto** 🛠️
        href : https://quarto.org/

    center:
      - text : "© 2024, François BOUSSENGUI"

    right: 
    - icon: instagram
      href: https://www.instagram.com/
    - icon: envelope
      href: mailto:f.boussengui@gmail.com 
  
  search: 
    location: navbar
    type: overlay
     
  navbar:
    right:
     
      - text: "Acceuil"    
        href: index.qmd

      - text: "Articles"
        href: posts/index.qmd
      
      - text: "Montres"
        href: posts_montres/index.qmd
        
      - text: "Montres" 
        menu:
          - text: Rolex
            href: posts_montres/rolex.qmd
          - text: Cartier
            href: posts_montres/cartier.qmd

      - icon: github
        href: https://github.com/
      - icon: instagram
        href: https://www.instagram.com/
      - icon: envelope
        href: mailto:f.boussengui@gmail.com
   
  
format:
  html:
    theme: theme.scss
    extensions: [fontawesome]
    googlefonts: 
      - family: "Roboto"
        weights: [400, 700]
      - family: "Merriweather"
        weights: [400, 700]
    toc: true
    pagetitle: "Gabonese Wrist | {{< meta title >}}"
    # le paramétrage de la grid permet d'éviter la sidebar et la margin 
    grid:
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem


editor: visual

comments:
  utterances:
    repo: francois-b-24/utterance

execute:
  freeze: auto